[main]
font=JetBrains Mono 12
dpi=96

[cursor]
style=beam
blink=yes
blink-rate=500

[colors]
background=060810
foreground=e2e8f0
selection-background=00d4ff26
selection-foreground=e2e8f0

# Normal
regular0=1a1f2c  # black
regular1=ef4444  # red
regular2=10b981  # green
regular3=f59e0b  # yellow
regular4=00d4ff  # blue
regular5=7c3aed  # magenta
regular6=06b6d4  # cyan
regular7=e2e8f0  # white

# Bright
bright0=334155
bright1=fca5a5
bright2=6ee7b7
bright3=fde68a
bright4=67e8f9
bright5=c4b5fd
bright6=a5f3fc
bright7=ffffff

[mouse]
hide-when-typing=yes
