# TOPU OS — Calamares Settings
# Calamares graphical installer configuration

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - grubcfg
    - bootloader
    - initcpiocfg    
    - initcpio
    - removeuser
    - umount
  - show:
    - finished

branding: topu
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
